sudo: required
services:
  - docker

before_install:
  - docker build -t chrismwas/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run chrismwas/react-test npm run test -- --coverage

after_success:
  - docker build -t chrismwas/multi-client ./client
  - docker build -t chrismwas/multi-nginx ./nginx
  - docker build -t chrismwas/multi-server ./server
  - docker build -t chrismwas/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #  Take those images and push them to docker hub
  - docker push chrismwas/multi-client
  - docker push chrismwas/multi-nginx
  - docker push chrismwas/multi-server
  - docker push chrismwas/multi-worker